dataset:
  data_dir: "CMAPSSData"

  files:
    FD001:
      train: "train_FD001.txt"
      test: "test_FD001.txt"
      rul: "RUL_FD001.txt"
    FD002:
      train: "train_FD002.txt"
      test: "test_FD002.txt"
      rul: "RUL_FD002.txt"
    FD003:
      train: "train_FD003.txt"
      test: "test_FD003.txt"
      rul: "RUL_FD003.txt"
    FD004:
      train: "train_FD004.txt"
      test: "test_FD004.txt"
      rul: "RUL_FD004.txt"

columns:
  id_col: "unit_number"
  time_col: "cycle"
  op_settings: ["op_setting_1", "op_setting_2", "op_setting_3"]
  sensors: ["sensor_1", "sensor_2", "sensor_3", "sensor_4", "sensor_5", "sensor_6", "sensor_7",
             "sensor_8", "sensor_9", "sensor_10", "sensor_11", "sensor_12", "sensor_13", "sensor_14",
             "sensor_15", "sensor_16", "sensor_17", "sensor_18", "sensor_19", "sensor_20", "sensor_21"]

eda:
  output_dir: "artifacts/eda"